import { SiteShell } from "./SiteShell";
import { CallToAction, ContactForm, PageHero, SectionHeader } from "./PageParts";
import { privacyHtml, termsHtml } from "../content/legal";

const qualities = "Good qualities Grevitywings want to see in every single candidate.If you have one these are the job skills we are looking for:Ambition -“Someone who is ambitious comes prepared to the interview and expresses lots of interest in the position. A candidate who wants to grow their career with the company can be an investment for the long term. Curiosity – It comes through during interviews when a candidate asks intelligent questions about the client company’s background and culture, as well as the role itself. Grit -“Show your grit by providing context for your achievements. For example, on a resume, instead of writing, Humility – “Humility goes a long way when it comes to driving good teamwork. It’s important to celebrate as a team but also to personally take responsibility for shortcomingsHustle- “Hustle doesn’t stem from talent; it is more about effort, ethics, attitude, and passion. If you’re prepared, willing to be coached, and want to go above and beyond, then you’ve got hustle.Learning agility- GrevityWings looking and probing for how resourceful the candidate was in their response to challenges and opportunities they faced. What did they learn, and how did it change them?” Positivity – “If a candidate doesn’t have a positive and upbeat demeanor, it’s a deal-breaker. To clarify, I’m not talking about a Pollyanna attitude, but rather someone who has a great attitude, smile, energy, and optimism that others feel when they interact with them. Reliability – Show you are reliable by [being on time] for interviews or meetings, and sending your resume and any other piece of documentation requested, when you promised.” —Angela Copeland, career and job search coach in MemphisTransparency – Be open and forthcoming. It’s OK to admit being terminated because of a difference of opinion with your boss, or a culture mismatch, or a mistake with a lesson learned.";

export function AboutPage() {
  const process = [
    ["Discover", "Discover the needs and requirements of clients, their pre-set criteria for the campaigns to help us in aligning with the operation team."],
    ["Design", "We implement the working of survey dialling in our featured CRM which checks the numbers against TPS and in-house DNC."],
    ["Deploy", "We categorise agents in batches based on several alike campaigns and they ask questions based on logic codes."],
    ["Deliveries", "Our delivery is taken care of MIS and it is ensured to provide delivery on client's respective portal within the deadline."],
  ];
  return <SiteShell><main id="main-content"><PageHero title="Welcome To Grevitywings Technologies​" eyebrow="About Us"/>
    <section className="section"><div className="container about-grid"><div className="about-image"><img src="/about-team.jpg" alt="Grevitywings team collaboration" width="768" height="576"/><div className="image-accent">Business With Brevity</div></div><div><SectionHeader label="Who Are We" title="About Us"/><p className="lead-copy">The Grevitywings Technologies has been created by directors who chose to remain anonymous humbly, by combining their 8 years of experience in lead generation, sales, digital marketing and IT services</p><p>With an overwhelming determination and desire to provide their clients with quality service and product, they worked day in day out to turn the dreams in reality by seizing the moment. Carpe Diem!</p><h3>What We Do</h3><p>We deal in various professional areas but we leap better in survey industry where we analyse the choices of people and turn into a business opportunity. We dial across diverse citizens of UK, take their consent, ask questions on their lifestyles and provide ways for opt-out too. A small team of passionate people who work diligently to ease the doing of business for our end clients. Our motto is Business with Brevity.</p></div></div></section>
    <section className="section process-section"><div className="container"><SectionHeader label="Our 4-D Process" title="Our 4-D Process"/><div className="process-grid">{process.map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section testimonials"><div className="container"><SectionHeader title={"Here's what some clients think of our work..."}/><p className="odd-copy">Coordinates for abs po oordinates for abs positioning the closest positioned Coordinates for abspositioning the closest positioned parent box of the positioned ting that ments.</p><div className="testimonial-grid"><blockquote>“Thanks to software, we’ve just launched our 5th website!” I made back the purchase price in just 48 hours! Man, this thing is getting better and better as I learn more about it. Thanks to software, we’ve just launched our 5th website!”<footer><strong>Diego Alejandro</strong><span>Whitero CEO, USA</span></footer></blockquote><blockquote>“We’ve seen amazing results already. I made back the purchase price in just 48 hours! Man, this thing is getting better and better as I learn more about it. Thanks to software, we’ve just launched our 5th website!”<footer><strong>Nicolas M. Salgo</strong><span>Slack inc.</span></footer></blockquote></div></div></section>
    <section className="section career-callout"><div className="container career-callout-grid"><div><SectionHeader label="Hunting for Jobs?" title="Hunting for Jobs?"/><p>The pandemic has turned many employers and careers upside down. While some careers may never recover, others are becoming more popular and important. If your career is one of the casualties of this situation, you are probably interested in changing your career because you need to continue earning your income. start with us we have Survey and sales Campaign.</p><a className="button button-primary" href="/index.php/career/">GET STARTED</a></div><div className="quality-card"><h2>Does your resume reflect your awesomeness?</h2><p>{qualities}</p><a className="button button-secondary" href="/index.php/career/">GET STARTED</a></div></div></section>
    <Stats/><CallToAction/>
  </main></SiteShell>;
}

export function Stats() { return <section className="stats-band"><div className="container stats-grid"><div><strong>1</strong><span>Surveyed</span></div><div><strong>—</strong><span>Happy clients</span></div><div><strong>—</strong><span>Campaigns completed</span></div></div></section>; }

export function ContactPage() { return <SiteShell><main id="main-content"><PageHero title="Contact Us" intro="If you feel like communicating with us for any query or grievance, fill the forms below. We will get back to you soon."/>
  <section className="section"><div className="container contact-layout"><div className="contact-info"><p className="eyebrow">Contact Us</p><h2>Contact Us</h2><div className="contact-method"><span>⌖</span><p>18, Rabindra Sarani Rd, Terita Bazar, Poddar Court, Tiretti, Kolkata, West Bengal 700001</p></div><div className="contact-method"><span>☎</span><a href="tel:+919831365785">98313 65785​</a></div><div className="contact-method"><span>✉</span><a href="mailto:info@grevitywings.com">info@grevitywings.com</a></div><div className="contact-socials"><span>Facebook</span><span>Twitter</span><span>WordPress</span><span>Dribbble</span></div></div><div className="form-panel"><ContactForm/></div></div></section>
  <section className="map-section"><iframe loading="lazy" title="Poddar Court, Kolkata" src="https://maps.google.com/maps?q=poddar%20court%20Kolkata&t=m&z=10&output=embed&iwloc=near"/></section>
  </main></SiteShell>; }

export function LegalPage({ type }: { type: "privacy" | "terms" }) { const privacy=type==="privacy"; return <SiteShell><main id="main-content"><PageHero title={privacy?"Privacy Policy":"Terms and Conditions"} eyebrow="Legal & Compliance"/><section className="section legal-section"><article className="container legal-copy" dangerouslySetInnerHTML={{__html:privacy?privacyHtml:termsHtml}}/></section></main></SiteShell>; }

export function GalleryPage() { return <SiteShell><main id="main-content"><PageHero title="Checkout Our Latest Team Gallery" eyebrow="Gallery" intro="The Simple Way to Keep Team Motivated – GrevitGallery"/><section className="section"><div className="container gallery-grid">{Array.from({length:6},(_,index)=><figure key={index}><img src={`/gallery/0${index+1}.jpg`} alt={`Grevitywings team gallery ${index+1}`} loading={index>1?"lazy":"eager"}/></figure>)}</div></section></main></SiteShell>; }

export const jobs = [
  {slug:"job/digital-marketing-executive-2-2-2",title:"Survey_International Voice Process WALKIN INTERVIEW_NEAR ACROPOLIS MALL KASBA",type:"Full-time"},
  {slug:"job/digital-marketing-executive-2-2",title:"UK Agent Representative-Kolkata",type:"Part-time"},
  {slug:"job/digital-marketing-executive-2",title:"UK Agent Representative",type:"Part-time"},
  {slug:"job/digital-marketing-executive",title:"Digital Marketing Executive",type:"Full-time"},
];

export function CareerPage() { return <SiteShell><main id="main-content"><PageHero title="Jobs" eyebrow="Career"/><section className="section career-section" id="jobs"><div className="container jobs-list">{jobs.map(job=><article key={job.slug}><div><span>{job.type}</span><h2>{job.title}</h2></div><a className="button job-view" href={`/index.php/${job.slug}/`}>View <span aria-hidden="true">↗</span></a></article>)}</div></section><section className="section career-story"><div className="container career-story-grid"><img src="/career.jpg" alt="Grevitywings careers" width="400" height="500"/><div><SectionHeader label="Career" title="We Build Lasting Relationships Between Candidates & Businesses"/><p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of “de Finibus Bonorum et Malorum” (The Extremes of Good and Evil) by Cicero, written in 45 BC.</p><a className="button button-primary" href="#jobs">Create an account</a></div></div></section></main></SiteShell>; }

const team = [
  ["Saba Hossain","CEO",""],
  ["Md Akram","CFO","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Martha Kaur","HR Manager","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Sushmita Sen","Compliance Head","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Sharique Almas","Tech Lead","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Jessica","Design Lead","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Zeeshan Hamid","Developer","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
  ["Fatma Benazir","QA Controller","Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore."],
];

export function TeamPage() { return <SiteShell><main id="main-content"><PageHero title="Our Team" eyebrow="Grevitywings Technologies"/><section className="section"><div className="container team-grid">{team.map(([name,role,body],index)=><article key={name}><img src={`/team/0${(index%6)+1}.jpg`} alt={name} width="300" height="300" loading={index>3?"lazy":"eager"}/><div><span>{role}</span><h2>{name}</h2>{body&&<p>{body}</p>}</div></article>)}</div></section></main></SiteShell>; }
